FROM nvcr.io/nvidia/pytorch:22.12-py3
# Install system packages
RUN apt-get update -yq &&\
    ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime &&\
    DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata &&\
    dpkg-reconfigure --frontend noninteractive tzdata &&\
    apt-get install -yq nodejs curl zsh zip git build-essential autoconf autopoint libtool &&\
    bash -c "$(curl -sL https://deb.nodesource.com/setup_18.x)"
# Install torch & jupyter
RUN pip3 install --upgrade pip&&\
    pip3 install git+https://github.com/MSeal/cython_hunspell.git@2.0.3 &&\
    pip3 install flask redis orderedset scikit-learn requests cython &&\
    pip3 install jupyter-resource-usage jupyterlab-git &&\
    ## Config jupyter to no password
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# Install requirements part 2
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Cleanup, setup workspace and move the .zshrc
RUN apt-get autoremove -yq && apt-get autoclean -y && apt-get clean -y &&\
    rm -rf requirements.txt /var/lib/apt/lists/* /tmp/* /var/tmp/* &&\
    mkdir -p /workspace/ &&\
    mv ~/.zshrc /workspace/.zshrc && \
    ln -s /workspace/.zshrc ~/.zshrc

# fix jupyter lab bug
RUN echo "c.NotebookApp.contents_manager_class = 'notebook.services.contents.largefilemanager.LargeFileManager'" > /root/.jupyter/jupyter_notebook_config.py 
WORKDIR /workspace/
EXPOSE 8888
SHELL ["/bin/zsh", "-c"]
# CMD jupyter notebook  --ResourceUseDisplay.track_cpu_percent=True --no-browser --port 8888 $CERTFILE_OPTION --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
CMD jupyter lab --ServerApp.open_browser=False --ExtensionApp.open_browser=False --LabApp.open_browser=False \
--port 8888 $CERTFILE_OPTION --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
