FROM nvidia/cuda:11.6.0-runtime-ubuntu20.04

# Install system packages
RUN apt-get update -yq &&\
    ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime &&\
    apt-get install -yq curl zip git build-essential python3 python3-pip libgl1 libglib2.0-0 &&\
    dpkg-reconfigure --frontend noninteractive tzdata &&\
    pip3 install --upgrade pip&&\
    ln -s /usr/local/bin/pip /usr/bin/pip3.8 &&\
    pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116 &&\
    pip3 install flask redis orderedset xgboost scikls it-learn gensim>=3.7.2 numpy requests cython &&\
# config jupyter to no password
    mkdir ~/.jupyter &&\
    echo "c.NotebookApp.token = u''" >> ~/.jupyter/jupyter_notebook_config.py
# Install requirements part 2
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Cleanup
RUN apt-get autoremove -yq && apt-get autoclean -y && apt-get clean -y &&\
    rm -rf requirements.txt /var/lib/apt/lists/* /tmp/* /var/tmp/* &&\
    mkdir -p /workspace/

# setup supervisord
WORKDIR /workspace/
EXPOSE 8888

CMD jupyter notebook  --ResourceUseDisplay.track_cpu_percent=True --no-browser --port 8888 $CERTFILE_OPTION --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root
