FROM nvidia/cuda:11.6.0-runtime-ubuntu20.04

# Install system packages
RUN Cloud9Deps='build-essential g++ libssl-dev python2.7 apache2-utils libxml2-dev sshfs wget' &&\
    export DEBIAN_FRONTEND=noninteractive &&\
    apt-get update -yq &&\
    ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime &&\
    echo "LC_ALL=en_US.UTF-8" >> /etc/environment &&\
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen &&\
    echo "LANG=en_US.UTF-8" > /etc/locale.conf &&\
    apt-get install -y locales &&\
    locale-gen en_US.UTF-8 &&\
    apt-get install -yq curl zip git nodejs $Cloud9Deps tmux libgomp1 procps curl zip git build-essential python3 python3-pip libgl1 libglib2.0-0&&\
    dpkg-reconfigure --frontend noninteractive tzdata &&\
    pip3 install --upgrade pip&&\
    pip3 install flask redis orderedset xgboost scikit-learn gensim>=3.7.2 requests cython &&\
# Install Cloud9
    git clone https://github.com/c9/core.git /opt/cloud9 &&\
    cd /opt/cloud9 &&\
    scripts/install-sdk.sh &&\
# Tweak standlone.js conf
    sed -i -e 's_127.0.0.1_0.0.0.0_g' /opt/cloud9/configs/standalone.js &&\
    apt-get purge -y --auto-remove $Cloud9Deps &&\
    apt-get autoremove -yq && apt-get autoclean -y && apt-get clean -y &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&\
# make working dir
    mkdir -p /workspace/

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
ENV PYTHONPATH /opt/xgboost/python-package:$PYTHONPATH NOMINATIM_SERVER=nominatim.openstreetmap.org

EXPOSE 80
EXPOSE 8888
CMD node /opt/cloud9/server.js --listen 0.0.0.0 --port 80 --auth $ACCESS_KEY:$SECRET_KEY -w /workspace/
