name: Docker Image CUDA126

on:
  push:
    branches: [ cuda126 ]
env:
  IMAGE_JUPYTER: masterid/jupyter:lab424-cuda126
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone main repo
      uses: actions/checkout@v2
    - name: free disk space
      run: |
        echo "Listing 100 largest packages"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt-get remove -y google-cloud-cli-anthoscli powershell firefox google-cloud-cli microsoft-edge-stable azure-cli llvm-14-dev llvm-15-dev google-chrome-stable dotnet-sdk-8.0 mysql-server-core-8.0 mono-devel
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile_Jupyter
        push: true
        tags: ${{ env.IMAGE_JUPYTER }}

