name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_JUPYTER: masterid/jupyter:lab-cuda116
  IMAGE_CLOUD9: masterid/cloud9:3.8
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone main repo
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile_Jupyter
        push: true
        tags: ${{ env.IMAGE_JUPYTER }}

