name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_JUPYTER: masterid/jupyter:cuda116
  IMAGE_CLOUD9: masterid/cloud9:3.8
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone main repo
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    # - name: Docker Build
    #   run: docker build . --file Dockerfile_Cloud9 --tag $IMAGE_CLOUD9
    # - name: Docker Push
    #   run: docker push $IMAGE_CLOUD9
    - name: Docker Build
     run: docker build . --file Dockerfile_Jupyter --tag $IMAGE_JUPYTER
    - name: Docker Push
     run: docker push $IMAGE_JUPYTER
