name: Docker Image CUDA126

on:
  push:
    branches: [ cuda126 ]
env:
  IMAGE_JUPYTER: masterid/jupyter:lab424-cuda126
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone main repo
      uses: actions/checkout@v2
    - name: free disk space
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/hostedtoolcache/
        sudo rm -rf /usr/local/graalvm/
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/node_modules
        sudo docker image prune --all --force
        
        APT_PARAMS='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
        $APT_PARAMS remove -y '^dotnet-.*'
        $APT_PARAMS remove -y '^llvm-.*'
        $APT_PARAMS remove -y '^php.*'
        $APT_PARAMS remove -y '^mongodb-.*'
        $APT_PARAMS remove -y '^mysql-.*'
        $APT_PARAMS remove -y azure-cli google-* google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
        $APT_PARAMS autoremove --purge -y
        $APT_PARAMS autoclean
        $APT_PARAMS clean
        df -h  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile_Jupyter
        push: true
        tags: ${{ env.IMAGE_JUPYTER }}

